name: Automatic Deployment to Staging

# Trigger the workflow when code is pushed to the development or staging branch.
on:
  push:
    branches:
      - Dev
      - Staging

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display Message for Dev
        if: github.ref == 'refs/heads/Dev'
        run: echo "Code changes committed to dev."

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/Staging'
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_STAGING }}
          dockerfile_directory: ./
          dockerfile_name: heroku_build/Dockerfile
          docker_options: "--no-cache"
          process_type: web

