name: Deploy to Heroku

# Run workflow on every push to main branch.
on:
  push:
    branches: [master]
    paths-ignore: README.md

# Your workflows jobs.
jobs:
   Dev:
     runs-on: ubuntu-latest
     environment: Dev
     steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build, Push and Release a Docker container to Heroku.
            uses: gonuit/heroku-docker-deploy@v1.3.3
            with:
              email: ${{ secrets.HEROKU_EMAIL }}
              heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
              heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
              dockerfile_directory: ./
              dockerfile_name: heroku_build/Dockerfile
              docker_options: "--no-cache"
              process_type: web

   Staging:
     runs-on: ubuntu-latest
     environment: Staging
     steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build, Push and Release a Docker container to Heroku.
            uses: gonuit/heroku-docker-deploy@v1.3.3
            with:
              email: ${{ secrets.HEROKU_EMAIL }}
              heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
              heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
              dockerfile_directory: ./
              dockerfile_name: heroku_build/Dockerfile
              docker_options: "--no-cache"
              process_type: web     
